### Get All Products
GET http://localhost:5000/api/products?minPrice=80&maxPrice=800&title=laptop

### Get Single Product
GET http://localhost:5000/api/products/6

### Create New Product
POST http://localhost:5000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlclR5cGUiOiJhZG1pbiIsImlhdCI6MTcyNjY2MjYyOSwiZXhwIjoxNzI2NzQ5MDI5fQ.ZKgMqDCWTuy2LrvGoVOA53JQd2vQIoQ1l2XGqvvGUtA

{
    "title": "my book in programming",
    "description":"about programmin",
    "price": 16
}

### Update Product
PUT http://localhost:5000/api/products/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlclR5cGUiOiJub3JtYWxfdXNlciIsImlhdCI6MTcyNjU3MjkyOCwiZXhwIjoxNzI2NjU5MzI4fQ.mxP3BPsj88tgDITbF33EKQAH3gGLZCrOqyD-XrvZSdY

{
    "title": "laptop updated"
}

### Delete Product
DELETE  http://localhost:5000/api/products/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlclR5cGUiOiJhZG1pbiIsImlhdCI6MTcyNzE3OTgwMywiZXhwIjoxNzI3MjY2MjAzfQ.nB5sab2JC8OXJ3_mDzw3hfYSk7PBaHmj6kz1q6GdZLw
